### ISSUE TITLE
External File System

### ISSUE THREAD

**Issue by philzook58** [ocsigen/js_of_ocaml#1199]
In the manual https://ocsigen.org/js_of_ocaml/dev/manual/options it states that the default directory for files added with `--file` go into `/`. In my experimentation, I believe they go into `/static/`? In addition, trying to use the custom directory option `--file /mytest.txt:/myfolder` returns a javascript file that errors out.
Ocaml 4.12.1 
js_of_ocaml 3.11.0+git-3.11.0-40-g91890b59-dirty
Simple example: https://gist.github.com/philzook58/584c64a6a1fdde6db3c984e8947114cb

**Comment by hhugo** [comment]
The manual is incorrect indeed.

Regarding the error you get, it's a cause by trying to print an actual error.

The printing is fixed by #1200.

The actual error is that one cannot "register a file" on an existing/real filesystem.
`--file mytest.txt:/myfolder` would work fine running in a webbrowser but fails running in nodejs.

`/static` is currently the only "dummy" filesystem registered by default when running with node.

**Comment by philzook58** [comment]
Thanks for the clarification!
