### ISSUE TITLE
[BUG?] `new%js Js_of_ocaml.Js.Unsafe.global##._CSSStyleSheet` causes "invalid constructor"

### ISSUE THREAD

**Issue by askvortsov1** [ocsigen/js_of_ocaml#1278]
**Describe the bug**
Reported in https://discuss.ocaml.org/t/full-stack-web-dev-in-ocaml-tutorial-w-dream-bonsai-and-graphql/9963/2?u=askvortsov, more details in same thread. 

I'm pretty sure the error comes from [this line](https://github.com/janestreet/ppx_css/blob/master/inline_css/src/inline_css.ml#L35), probably as a result of [this unsafe module](https://github.com/janestreet/ppx_css/blob/master/inline_css/src/inline_css.ml#L4-L22). It comes up as an invalid constructor on Firefox and Safari, but works fine on Chrome. Since behavior is different across browsers, this feels like it might be a Js_of_ocaml issue, although I'm not familiar with its inner workings.

**Versions**
OCaml 4.13.1
Js_of_ocaml 4.0.0

**Comment by pmwhite** [comment]
This is not related to `js_of_ocaml`, since, as you pointed out, the offending line is in `ppx_css`. The root bug is that Chrome implements the `CSSStyleSheet()` constructor, but [firefox does not](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/CSSStyleSheet); well, actually firefox just keeps it behind the `layout.css.constructable-stylesheets.enabled` feature flag, which you can access by visiting `about:config`.

I recommend this issue be closed. You could re-open it in the ppx_css repo if you want.
