### ISSUE TITLE
[BUG] Performance issue with Yojson

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#1703]
Parsing a large string (~ 1MiB) with Yojson is really slow. We should investigate why.

**Comment by hhugo** [comment]
How slow is really slow ? Are you sure the slowness comes from yojson ? Can you describe the issue a bit more ?

**Comment by hhugo** [comment]
I see. I was able to reproduce.
- `Yojson.Raw.from_string` is not (much less) affected because it processes the whole string at once.
- `--disable use-js-string` solves the issue
- We should probably fix theses patterns in the ocaml/ocaml codebase
- We should revisit the decision to change the underlying representation of bytes when converting to string (when use-js-string is enabled)

**Comment by hhugo** [comment]
@vouillon, see https://github.com/ocaml/ocaml/pull/13543

**Comment by vouillon** [comment]
Cool! Thanks!

**Comment by hhugo** [comment]
- https://github.com/ocaml/ocaml/pull/13543 has been merged.
- #1713 alone fixes most of the issue reported here
- #1712 might need more testing to understand the impact
