### ISSUE TITLE
0 always first element in array argument when binding to external JS function.

### ISSUE THREAD

**Issue by nosman** [ocsigen/js_of_ocaml#317]
As in the title, when I pass in an array argument from Ocaml to an external JS function, there is always a 0 stored in index 0 of the array. 
Is this expected?

**Comment by alainfrisch** [comment]
That's how OCaml array are encoded by js_of_ocaml.  To pass an array to a JS function, you need to translate it first to a JS array (i.e. a value of type `'a Js.js_array Js.t`) using the `Js.array` function.

**Comment by adrien-n** [comment]
I've just stumbled upon the same issue. I was fairly sure not converting values was the root cause but somehow I couldn't think of the array conversion. I think that part of the issue was my use of Js.Unsafe.inject but I don't think I could do it differently (I was building an array of JS objects). I find inject to be very difficult to use properly, on par with C bindings because it takes 'a as first argument. Is there any hope to get another function that has a less dangerous prototype?

**Comment by TyOverby** [comment]
@adrien-n : how about `Js.array`?

```ocaml
val to_array : 'a js_array t -> 'a array
(** Conversion of arrays from Javascript to OCaml. *)
```

**Comment by adrien-n** [comment]
Yes, that's how I've done it in the end but I find the use of the Unsafe module particularly difficult while it isn't exceptionnal to have to use it. That's why I think there should be some changes to make it less dangerous to use.

What I needed was an object like '{ foo: [ { "bar": "baz" } ] }'. It took me a long time to get there (I'm not sure I'm done actually). That doesn't seem like an exceptional usecase, yet it's definitely not easy to do currently.

**Comment by TyOverby** [comment]
The Unsafe module is indeed quite unsafe; but it shouldn't be necessary to do what you want. 

Is the following code acceptable?

```ocaml
let my_object = object%js
  val foo = Js.array [| 
    object%js 
      val bar = Js.string "baz" 
    end  
  |]
end
```

**Comment by hhugo** [comment]
> Is there any hope to get another function that has a less dangerous prototype?

Do you have any suggestion ?

**Comment by adrien-n** [comment]
@TyOverby's suggestion is pretty good for my usecase. I was looking at the Unsafe module because I knew I could do what I needed with it but I was unsure how. For my usecase, a note next to Unsafe.obj with a link to the corresponding section of the bindings page would probably have been pretty helpful.

I think the documentation also lacks a section with examples for constructing JS objects. I actually spent a fair bit of time wondering whether I had to use Js.array or not because the typing doesn't help.

For reference, with @TyOverby's suggestion, my code is as follows:

            ops
            |> Array.of_list
            |> Array.map (function
              | `Text s ->
                  (object%js val insert = Js.bytestring s end :> < > Js.t)
              | `Simple i when i < 0 ->
                  (object%js val delete = -i end :> < > Js.t)
              | `Int i when compare i Int64.zero < 0 ->
                  (object%js val delete = - Int64.to_int i end :> < > Js.t)
              | `Simple i ->
                  (object%js val retain = i end :> < > Js.t)
              | `Int i ->
                  (object%js val retain = Int64.to_int i end :> < > Js.t)
              | x ->
                  Printf.eprintf "Parsing failure: got %S\n" (CBOR.to_diagnostic x);
                  assert false
            )
            |> (fun ops -> object%js val ops = Js.array ops end)
            |> compose empty

It feels quite heavy and I'm still able to write "val ops = ops" instead of "val ops = Js.array ops" unfortunately.
