### ISSUE TITLE
did js_of_ocaml try to explore google closure compiler advanced mode?

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#340]
for global dead code analyzer? this should work well for bytecode in  theory

**Comment by zakki** [comment]
Google closure compiler removes unreferenced function arguments. That breaks partial function applications.

**Comment by bobzhang** [comment]
would you mind show me a concrete example?

**Comment by zakki** [comment]
js_of_ocaml relies on Function.length.
https://gist.github.com/zakki/85593f1cbf1fddb0c2a5

**Comment by bobzhang** [comment]
Thanks for the info. could it be resolved by reading signatures which can tell the arity of function

**Comment by copy** [comment]
It's possible to create a build of Closure Compiler without this specific optimisation. See: https://github.com/google/closure-compiler/blob/0e7a80ab154fe73dd594ded9d263560bbfcdc3b0/src/com/google/javascript/jscomp/CompilerOptions.java#L476

**Comment by fdopen** [comment]
It's not enough. Functions arguments are also removed by other options, see e.g:
https://github.com/google/closure-compiler/blob/270d50976fe84911acee4226a88268ef1285ae08/src/com/google/javascript/jscomp/RemoveUnusedVars.java#L369
If this function is called or not, doesn't seem to depend on `optimizeParameters`. It depends on otherwise useful options ...
