### ISSUE TITLE
Array is from global object

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#351]
Hi, I have a special issue with js_of_ocaml, now it generates code which sometimes contain "$.Array"
$ is a global object, this works perfectly fine in most cases.
In bloomberg, we have a customized js engine, which removes such global object semantics, if I replace "$.Array" with "Array", it works fine
Is there any reason that we use "$.Array" instead of "Array"?
Thanks for your time

**Comment by hhugo** [comment]
It comes from

https://github.com/ocsigen/js_of_ocaml/blob/562fd3091a11cc46bbfeb65d64efb7260c54f2ee/lib/js.ml#L242

and was introduced by https://github.com/ocsigen/js_of_ocaml/commit/a490a08fe85d40c8af091e786ac8942f18508717

in your example, the `$` should come from the main function

```
(function($){ .... $.Array ... }(function(){return this}()))
``` 

There is no specific reason for using `global_object.Array` instead of `Array`.
I'm not sure what you mean by `which removes such global object semantics`

**Comment by bobzhang** [comment]
in our customized js engine, there is no global variable. in normal js, if you say this.Array in the toplevel, it will be resolved to be Array, in our js engine, this will cause an exception raised

**Comment by bobzhang** [comment]
would you mind revert part of the commit a490a08 ?

**Comment by hhugo** [comment]
The global_object is used in many places in the runtime.  I think you need more than a partial of this commit. What about making a PR ?

**Comment by bobzhang** [comment]
sure, will do : )

**Comment by bobzhang** [comment]
I need check with the legal department of my employer before sending a PR, sorry for the delay

**Comment by hhugo** [comment]
reopen if this is still relevent
