### ISSUE TITLE
tyxml in  < 2.7 doesn't work with reactiveData 0.2

### ISSUE THREAD

**Issue by dsheets** [ocsigen/js_of_ocaml#412]
See [this Travis failure](https://travis-ci.org/ocaml/opam-repository/jobs/104869223#L743) where `ReactiveData.RList.nil` is not found.

**Comment by hhugo** [comment]
I believe the title should be js_of_ocaml < 2.7 doesn't work with reactiveData 0.2

**Comment by smondet** [comment]
@hhugo I've been using `js_of_ocaml` 2.6 with `reactiveData` 0.1 without problem.

This PR creates a problem for me:
https://github.com/ocaml/opam-repository/pull/5496/files
it's an arbitrary constraint on reactiveData >= 0.2 for any JSOO version.

Ketrew 2.0.0 uses JSOO 2.6 and reactiveData 0.1 and does not work with reactiveData 0.2 because of the API changes:
(not more `make_from` function https://github.com/hammerlab/ketrew/issues/329)

**Comment by vasilisp** [comment]
@smondet, ocaml/opam-repository#5496 adds a conflict with `reactiveData >= 0.2`, not a dependency on `reactiveData >= 0.2`. So JSOO 2.6 with reactiveData 0.1 should be allowed.

`make_from` is now called `from_event`. See ocsigen/reactiveData#15 and the discussion in ocsigen/reactiveData#14.

**Comment by smondet** [comment]
@vasilisp Indeed thanks !
 (I misread the PR + there was race condition; my user hit the problem before the PR; and I investigated right after I guess :) )
