### ISSUE TITLE
Starting a utility library. 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/js_of_ocaml#497]
I initially had started a utility library for jsoo but I think it would be better to just package it with jsoo itself rather than suffer a JS like fate of a million little utility libraries. 

for example, have one PR open for is_null, but I want to add much more. (especially for transitions to OCaml land and back)

**Comment by vasilisp** [comment]
Can you sketch the contents of such a library? What would its scope be, *e.g.,* compared to `Js` and its submodules (especially `Js.Opt`, `Js.Optdef`, and `Js.Unsafe`), which already provide such facilities?

**Comment by fxfactorial** [comment]
Sure, basically like this: https://github.com/fxfactorial/runa but instead with the library itself, just practical functions that make using js_of_ocaml easier.

**Comment by hhugo** [comment]
I had a quick look at `runa`.


> (** Easy access of field by name from JS Object *)
> val ( <!> ) : 'a -> 'b -> 'c
(** Alias of Js.Unsafe.meth_call*)
val m : 'a -> string -> Js.Unsafe.any array -> 'b
> (** Alias of Js.Unsafe.inject *)
> val ( !! ) : 'a -> Js.Unsafe.any

I don't think it's a good idea to provide short/cryptic operator for unsafe feature.


> (** Combine two JS objects into one *)
> val merge : 'a -> 'a -> < .. > Js.t
> (** Create a JS object out of a Jstable *)
> val object_of_table : Js.Unsafe.any Jstable.t -> 'a

How often do you need these ?


> (** Parse a string as JSON *)
> val json_parse : string -> 'a
> (** Try to get a string out of given Object *)
> val stringify : 'a -> string

This is `Js._JSON` acting on `string` instead of `Js.js_string.t` .. why not   

> (** Set the global variable DEBUG_VAR to whatever object you
>     provide, useful during debugging *)
> val debug : 'a -> unit

I don't like that there is unique global variable for debug

> (** Log any object to the console *)
> val log : 'a -> unit

I think is a good idea to provide helper for Firebug. I'm afraid `log` `info` `error` would pollute the scope too much if we include them in js.ml

> (** In [set_interval ~every cb], call !{cb} every given seconds.*)
> val set_interval : every:float -> (unit -> unit) -> Dom_html.interval_id

This should definitively go next to `Dom_html.setTimeout` 

> (** Call your function with the scope of JavaScript's this object,
>     very useful *)
> val with_this : ('a -> 'b) -> Js.Unsafe.any

Why very useful ? Why  `Js.Unsafe.any`

> (** Turn JavaScript string array into OCaml list of string *)
> val to_string_list : Js.string_array Js.t -> string list
> (** Turn OCaml list of strings into JavaScript string array *)
> val of_string_list : string list -> Js.js_string Js.t Js.js_array Js.t
> (** Get the current UNIX time *)
> val time_now : unit -> float

This could go in `js.ml` 

> (** Get all keys of an Object *)
> val keys : Js.Unsafe.any -> string list
> (** For each item in the object, call function and ignore results *)
> val for_each_iter : f:('a -> 'b) -> Js.Unsafe.any -> unit
> (** For each item in the object, call function and keep results *)
> val for_each_map : f:(string -> 'a -> 'b) -> Js.Unsafe.any -> 'b list

This is `Js.object_keys`, do you really need all that ?
