### ISSUE TITLE
Discussion: raise exception and catch exception

### ISSUE THREAD

**Issue by bobzhang** [ocsigen/js_of_ocaml#513]
I saw jsoo does not intercept `throw`, instead, when an exception is raised, it will intercept it with `caml_wrap_exception`.

Any reason why it does not do it? the problem with `throw` a plain value is that you lose most benefits of an exception: a whole stack trace when it is  uncaught

**Comment by hhugo** [comment]
`caml_wrap_exception` is only used to convert regular JavaScript exceptions into ocaml ones.

There are some experiment to embed a JavaScript error inside an ocaml exception so that we have access to the backtrace [1], but it doesn't work well on constant exceptions 

Do you have anything to propose ?

[1] `https://github.com/ocsigen/js_of_ocaml/compare/bt?expand=1`.

**Comment by bobzhang** [comment]
I noticed that `new Error ` is very expensive, so it might only work in debug mode.

Why it does not work well on constant exceptions? suppose you wrap all OCaml exceptions in 
`MlError` class (which inherits from `Error` class)

**Comment by vouillon** [comment]
Historically, we were just throwing OCaml exceptions, and not bothering to wrap intercepted JavaScript exceptions, as this was the simplest thing to do.
@hhugo added `caml_wrap_exception` so as not to get weird errors when intercepting JavaScript exceptions.
