### ISSUE TITLE
Evaluation ocaml code in the browser

### ISSUE THREAD

**Issue by viebel** [ocsigen/js_of_ocaml#528]
What is the way to evalutate dynamic ocaml code in the browser?

Like you guys do in http://ocsigen.org/js_of_ocaml/2.8.2/files/toplevel/index.html ?

Is there a `javascript` file that implements a `eval` function that receives `ocaml` code and evaluate it?

**Comment by viebel** [comment]
@m2ym @unhammer @ttamttam could you help on this?

**Comment by unhammer** [comment]
I don't know, but I suspect https://github.com/ocsigen/js_of_ocaml/commit/21ce69e27c67349ea819cc92f52c45335eca24a7 gives some hints :-)

**Comment by viebel** [comment]
I tried to look at it but it's really complicated.
All I need is a `js` file and a function to call.

**Comment by Drup** [comment]
@viebel http://ocsigen.org/js_of_ocaml/2.8.2/api/JsooTop ?

**Comment by viebel** [comment]
@Drup I need something much simpler: a javascript file that exposes a javascript function (something link `eval_ocaml_code`) that evaluates ocaml expressions passed to it as strings.

makes sense?

**Comment by dannywillems** [comment]
@viebel It means you have to compile the OCaml code no?

**Comment by viebel** [comment]
I'm not sure I understand what you mean.

In  http://ocsigen.org/js_of_ocaml/2.8.2/api/JsooTop I don't see any javsacript function that evaluates ocaml code

**Comment by Drup** [comment]
Well, it's an ocaml function that you can compile to javascript, so it's a javascript function too :)
See the manual on reverse bindings [here](http://ocsigen.org/js_of_ocaml/2.8.2/manual/export).

**Comment by dannywillems** [comment]
@Drup I think it is not @viebel wants. I think @viebel wants a function which can be called in JavaScript that executes OCaml code. This function is defined in another JavaScript file, and never js_of_ocaml is called from the command line. I think it's something like your server-side idea you exposed in the last meeting. Except here it's always client-side.

**Comment by viebel** [comment]
Exactly @dannywillems. And I am pretty sure that there is such a function in one of the scripts loaded in  http://ocsigen.org/js_of_ocaml/2.8.2/files/toplevel/index.html.

But I was not able to find it.

I hope you guys could help...

**Comment by dannywillems** [comment]
Like `Js.Unsafe.js_expr`, but in this case, it will evaluate OCaml code and gives the output.
For example
```JavaScript
var x = eval_ocaml_code("let x = 2 in print_int 2");
console.log(x)
```
outputs
```
2
```

**Comment by viebel** [comment]
This is exactly what I am looking for...

So: is there `eval_ocaml_code` in javascript somewhere?

**Comment by dannywillems** [comment]
@viebel I asked to @vouillon: it is not simple. The toplevel http://ocsigen.org/js_of_ocaml/2.8.2/files/toplevel/index.html has an OCaml compiler and `js_of_ocaml`. It was I thought with my first comment. You need to compile the OCaml code to bytecode and after that, compiles it to JavaScript. So it requires both.

**Comment by Drup** [comment]
@viebel What I linked *is* what you want: it's a function that takes a string of ocaml code and evaluate it. It uses both the ocaml compiler and js_of_ocaml, compiled to javascript via js_of_ocaml itself (it's circular!). It's only client-side, since it was all compiled via js_of_ocaml. 

You won't find a "simple" javascript interpreter for OCaml. Writing such interpreter by hand would be a gigantic undertaking, and it seems of limited use since you can get it "for free" by reusing the source code of the ocaml compiler itself (which makes it, if not correct, at least consistent with the normal ocaml toplevel).

**Comment by Drup** [comment]
Is there a reason you don't want to use the `JsooTop` module ? If the goal is to evaluate OCaml code in javascript, it's probably the best solution.

**Comment by viebel** [comment]
I would be really happy to use the `JsooTop` module. 
I was expecting that it is already built in javascript somewhere and I could use it with zero effort :)

**Comment by bobzhang** [comment]
@viebel if you dont mind, we have this out of box: https://github.com/bloomberg/bucklescript/issues/629 
(currently powered by both jsoo and bucklescript), it is significantly smaller than jsooTop and the compilation should be faster since we did much less work, only around 500KB gzipped.
As a community, any software written in OCaml would benefit each other.

**Comment by viebel** [comment]
@bobzhang thanks
