### ISSUE TITLE
Deriving Json: type inference issue

### ISSUE THREAD

**Issue by vouillon** [ocsigen/js_of_ocaml#552]
The expression ``[%derive.json: [`A]]`` has type ``[> `A ] Deriving_Json.t``, which is incorrect.

The reason is that the encoding function contains a catch-all case:
```ocaml
(fun buf  ->
   fun a  ->
     match a with
     | `A -> Deriving_Json.Json_int.write buf 65
     | _ -> assert false)
```
Thus, it indeed accepts other variants but fails for them...

@vasilisp, do you know the reason for this catch-all case?

**Comment by vasilisp** [comment]
Good catch. Consider this:

```ocaml
type foo = [`Foo]
[@@deriving json]

type bar = [`Bar | foo]
[@@deriving json]
```

This produces the following `bar_to_json`:

```ocaml
let rec (bar_to_json : Buffer.t -> [> bar] -> unit) =
  ((let open! Ppx_deriving_runtime in
      fun buf  ->
        fun a  ->
          match a with
          | `Bar -> Deriving_Json.Json_int.write buf 3303859
          | #foo -> foo_to_json buf a
          | _ -> assert false)
  [@ocaml.warning "-A"])
```

and a similar `foo_to_json`. If `foo_to_json` wasn't polymorphic, we wouldn't be able to call `foo_to_json` from `bar_to_json`, because the compiler doesn't know that `a` can be coerced to `foo` in that match case.

We could produce a less constrained copy of `foo_to_json` just for this case. Any better ideas?

**Comment by Drup** [comment]
@vasilisp Just use `as` for the `#foo` case: 

```ocaml 
let rec (bar_to_json : Buffer.t -> bar -> unit) =
  ((let open! Ppx_deriving_runtime in
      fun buf  ->
        fun a  ->
          match a with
          | `Bar -> Deriving_Json.Json_int.write buf 3303859
          | #foo as a -> foo_to_json buf a)
  [@ocaml.warning "-A"])
```

**Comment by vasilisp** [comment]
Thanks! It didn't occur to me that `as` restricts the type...
