### ISSUE TITLE
Function equality (and difference) does not throw exception

### ISSUE THREAD

**Issue by jmid** [ocsigen/js_of_ocaml#584]
Consider the program
```
  let m = (=) (fun g -> "") (fun v -> "") in 0
```
If I compile it to ocaml bytecodes and run it it raises an exception as expected:
```
$ ocamlc -o issues/eqfun.byte ./issues/eqfun.ml 
File "./issues/eqfun.ml", line 2, characters 6-7:
Warning 26: unused variable m.
$ ./issues/eqfun.byte 
Fatal error: exception Invalid_argument("compare: functional value")
$ 
```
However with js_of_ocaml the exception disappears:
```
$ js_of_ocaml -o issues/eqfun.js issues/eqfun.byte 
$ node issues/eqfun.js 
$ 
```

There is a similar issue with the difference operator, e.g., if I change `(=)` to `(<>)` in the above example I observe the same difference in behaviour. However with, e.g., the operator `compare` js_of_ocaml will produce code that raises an exception.

This is with ocaml version 4.04.0, js_of_ocaml version 2.8.4, and node version 6.10.3.

**Comment by hhugo** [comment]
Thanks for the report.
The exception disappear with js_of_ocaml because the js_of_ocaml compiler considers that this expression is unused, has no side effect and removes it.

The following would behave as expected.
```
let m = (=) (fun g -> "") (fun v -> "") in if m then assert false
```

The culprit is https://github.com/ocsigen/js_of_ocaml/blob/master/runtime/stdlib.js#L411
A fix would be:
```
//Provides: caml_equal (const, const)
```

**Comment by hhugo** [comment]
This has been fixed at some point
