### ISSUE TITLE
joo_global_object is undefined when bundled in strict mode

### ISSUE THREAD

**Issue by copy** [ocsigen/js_of_ocaml#699]
jsoo uses this compilation scheme to detect the global object:

```
(function(joo_global_object)
   {"use strict";
       console.log(joo_global_object);
       // ...
   }
  (function(){return this}()));
```

This fails when the generated JavaScript is bundled together with other JavaScript files that have a global `"use strict";` stanza, as `this` doesn't become the global object in strict mode.

**Comment by thangngoc89** [comment]
You can compile with `--wrapWithFun` flag and initialize the script yourself

**Comment by copy** [comment]
> You can compile with --wrapWithFun flag and initialize the script yourself

Good point, that's what I'll do.

Still would be nice to have it working within jsoo, for example using `Function("return this")()`.

**Comment by hhugo** [comment]
Where did you find the `Function("return this")()` solution ?

**Comment by copy** [comment]
Here: https://stackoverflow.com/a/3277192

**Comment by cannorin** [comment]
Any update on this? This is still an issue since #710 is reverted.

**Comment by cannorin** [comment]
Quick survey shows that you can change `this` to an arbitrary variable if you pass `` `Custom "some_name" `` to `~global`: https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/bin-js_of_ocaml/compile.ml#L56-L59

But there is no command line option to do that: https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/bin-js_of_ocaml/compile.ml#L56-L59

**Comment by jchavarri** [comment]
I just ran into this issue due to some misconfiguration on the `html` file that was loading the jsoo bundle with `<script type="module" .. />` attribute. And apparently modules [use `strict` mode automatically](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts).

Is there anything preventing jsoo to use [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead of `this`? Browser support [seems to be quite good](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility), and oldest Node version supported is 12, which is already in [maintenance LTS](https://nodejs.org/en/about/releases/).
