### ISSUE TITLE
Function does not get exported if its name has underscores

### ISSUE THREAD

**Issue by cwfoo** [ocsigen/js_of_ocaml#717]
This export shown below does not work correctly. `my_function` is not accessible from JavaScript:

```ocaml
let my_function _ =
  Js.string "Hello!"

let () =
  Js.export_all (
    object%js
      val my_function = my_function
    end)
```

However, if I change `val my_function = my_function` to `val myFunction = my_function`, `myFunction` can be called from JavaScript. Why is this?

**Comment by sagotch** [comment]
It is not lazyness, but I will juste quote docs since I do not think I would explain it better. I think that it is the reason why:

>  Method name and underscore
Some overloading is possible using a syntactic trick: names _foo, foo_abcd and foo are all mapped to a same Javascript field name foo: when accessing a field of an object, the name given in the OCaml code is transformed by removing a leading underscore and then removing all characters starting from the last underscore; this yields the corresponding Javascript name.

Taken from https://ocsigen.org/js_of_ocaml/dev/manual/library
